#!/bin/sh

set -e

# Let this be run from any directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
cd ..

CURRENT_VERSION=`node -e 'console.log(require("./lerna.json").version)'`

# Delete the version tag that was generated by "lerna version" 
git tag --delete "v$CURRENT_VERSION"
git push --delete upstream "v$CURRENT_VERSION"

# Tag the current commit as the new version
git tag "v$CURRENT_VERSION"
git push upstream "v$CURRENT_VERSION"

# Publish the SDK from the current git HEAD
lerna publish from-git
